services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: drupal_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - drupalnet

  nginx:
    image: nginx:stable
    container_name: drupal_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - drupalnet

  db:
    image: mariadb:10.5
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupalnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: drupal_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - drupalnet

networks:
  drupalnet:

volumes:
  db_data:
